### PR TITLE
Fix specify config file not work while installing

### PR DESCRIPTION
**Pull request by coldnight**
Via `pre-commit install -c .other-config.yaml`

### CODE REVIEW

**Comment by coldnight** [comment]
@asottile Please review and I don't how to handle the hash things [here](https://github.com/pre-commit/pre-commit/blob/master/pre_commit/commands/install_uninstall.py#L14-L22).

**Comment by asottile** [comment]
Looks great!  I haven't changed the hashes in forever and don't think they need to change -- iirc they're only if the calling construct of pre-commit changes.

Could you add a quick test that demonstrates that this works?  There should be some prior art in `tests/commands/install_uninstall_test.py`

**Comment by asottile** [comment]
Oh neat, I was able to add a test to your branch directly.

**Comment by asottile** [comment]
Thanks for the PR!  This will make it into the next release I have (I have some plans to add a few more things into this one as well)

**Pull request merged**
