### PR TITLE
Fix broken Azure Pipelines badge link references

### PR DESCRIPTION
**Pull request by int3l**
Current links lead to 404 Page.

### CODE REVIEW

**Comment by int3l** [comment]
Welp... this is the MicroSoft's way of "doing" stuff :D

**Comment by asottile** [comment]
they still suggest the url I had in the badging dropdown, so I suspect this is an accidental bug on their side.  going to wait for a response on twitter

**Comment by int3l** [comment]
Yeah, [microsoft/calculator](https://github.com/microsoft/calculator)'s badge seems to be broken too.

**Comment by asottile** [comment]
seems this is the issue to upvote: https://developercommunity.visualstudio.com/content/problem/1064899/status-badge-of-build-pipeline-leads-to-404-not-fo.html

**Comment by int3l** [comment]
I hope that they will fix it eventually :)

**Pull request closed without merging**
