### PR TITLE
Improve help text

### PR DESCRIPTION
**Pull request by brettmcintosh**
Add choices to --color help text.
Fix typo in --allow-unstaged-config.

### CODE REVIEW

**Comment by asottile** [comment]
you've failed the pre-commit hooks, please fix and :shipit: :)

**Comment by asottile** [comment]
Thanks!

**Comment by asottile** [comment]
fwiw, I took it one step further with `argparse`'s `metavar`: https://github.com/pre-commit/pre-commit/commit/eb6da4ae103fd086f11099cd0c463b9c62edd544

Now looks like this:

```
$ pre-commit run --help
...
  --color {auto,always,never}
                        Whether to use color in output. Defaults to `auto`.
...
```

**Comment by brettmcintosh** [comment]
Much better.

**Pull request merged**
