### PR TITLE
Properly detect if commit is a root commit

### PR DESCRIPTION
**Pull request by samskiter**
Fix bad check for ancestor root commits.

### CODE REVIEW

**Comment by samskiter** [comment]
If you want to write a test, you need 
EITHER
a new repo and a remote to push to (you could use a local-filesystem remote)
OR
just add a new remote to a repo (again, you can use a local-filesystem remote)

THEN
attempt to push to the remote

When you hit line 14 (`source=$(git rev-parse "$first_ancestor"^)`) the git rev-parse will fail as it tries to find the commit before the root commit. The error looks like:
```
$ git rev-parse ROOT_SHA^
ROOT_SHA^
fatal: ambiguous argument 'ROOT_SHA^': unknown revision or path not in the working tree.
```
Here's a set of commands you can use to repro the issue:

```
cd
mkdir testing
cd testing
mkdir remote
cd remote/
git init --bare
cd ..
mkdir local
cd local
git init
git touch blah
touch blah
git add blah
git commit -m "my root commit"
touch blee
git add blee
git commit -m "my second commit"
git remote add origin ~/testing/remote
pre-commit install -t pre-push
touch .pre-commit-config.yaml
git push origin master
```

**Comment by samskiter** [comment]
Related issue: https://github.com/pre-commit/pre-commit/issues/693

**Comment by asottile** [comment]
Awesome! Thanks for the reproduction steps as well, they were very helpful for adding a test :)

**Comment by asottile** [comment]
This is now released as part of [1.5.1](https://github.com/pre-commit/pre-commit/releases/tag/v1.5.1)!

**Pull request merged**
