### PR TITLE
Fix bug - pushing on an empty changeset

### PR DESCRIPTION
**Pull request by barrysteyn**
There is a problem when pushing an empty changeset - the command `pre-commit --hook-stage push` will be run. But actually, if the changeset is empty, there is nothing to push (everything is up to date). So we should just exit.

### CODE REVIEW

**Comment by barrysteyn** [comment]
@asottile If we try push an empty change set, `pre-commit --hook-stage push` will be run resulting in an error. I have submitted a PR to fix this. If you think there is a better way to do this, then please change.

**Comment by asottile** [comment]
I PR'd your PR :)

**Comment by asottile** [comment]
@barrysteyn  the nice bit about me PRing your PR is I can just merge it now :P

**Comment by asottile** [comment]
This is available in version 0.6.1

**Pull request merged**
