### PR TITLE
exclude GIT_SSL_NO_VERIFY env variable from getting stripped

### PR DESCRIPTION
**Pull request by schiermike**
Can this change please get merged? We sit behind a proxy that messes with certificates...

### CODE REVIEW

**Comment by asottile** [comment]
that's actually kinda terrifying -- doesn't this variable expose you to all sorts of malicious MITM?

I'm looking into why windows CI is failing -- I suspect a bad azure pipelines release :(

**Comment by asottile** [comment]
I've opened https://github.com/microsoft/azure-pipelines-image-generation/issues/1468 for the `git` issue

**Comment by schiermike** [comment]
Yeah, a bit yes. The proxy itself is pretty restricting and only allows connections to a handful of public domains such as github.com - and it does verify certs. So it's only a matter of trusting the path to the proxy inside the company network ...

**Comment by asottile** [comment]
this has been released as part of [v2.0.0](https://github.com/pre-commit/pre-commit/releases/tag/v2.0.0) -- thanks again for the patch!

**Pull request merged**
