### PR TITLE
Add missing help to --verbose param

### PR DESCRIPTION
**Pull request by touilleMan**
Hi again,

I noticed `--verbose` is missing its help ;-)

### CODE REVIEW

**Comment by asottile** [comment]
it does a little bit more than that but also "verbose" is usually self explanatory

**Comment by touilleMan** [comment]
> it does a little bit more than that but also "verbose"

FYI I took the verbatim text from the [pre-commit hooks documentation](https://pre-commit.com/#pre-commit-configyaml---hooks), so maybe it should be updated then (or removed entirely given it is self explanatory :clown_face: )

image

**Comment by asottile** [comment]
that's a hook configuration not the commandline 🤡

**Comment by touilleMan** [comment]
> that's a hook configuration not the commandline 🤡

My bad, I was [pointing the wrong place](https://pre-commit.com/#pre-commit-run)

image

anyway, I won't be wasting any more of your item

**Pull request closed without merging**
