### PR TITLE
Check if --config option is a path to a regular file

### PR DESCRIPTION
**Pull request by geieredgar**
This change implements the suggestion made by @asottile in #1037 
I tried to be compatible to the current behavior of `_adjust_args_and_chdir(args)`, therefore we also check if the path points to a file relative to the git root directory.

If there is some interest in getting this merged I will add/fix the required tests.

### CODE REVIEW

**Comment by asottile** [comment]
hmmm this is interesting, I'll have to think about this more

the interesting / challenging part of this is there's commands that accept `--config` but don't do anything with it (`gc` / `clean` / `sample-config`, and maybe probably the brand new `init-templatedir` probably should as well) -- in these cases it isn't super important that `.pre-commit-config.yaml` resolves to a file which exists, but sometimes (rarely) that argument is used just as a string

the other problem with doing more clever parsing at the `argparse` stage is we don't properly have enough error handling set up to produce a useful trace (for instance, if a command is called when outside of a `git` repository)

I'll have to put more thought into this :thinking:

**Comment by geieredgar** [comment]
@asottile Now the path checking should be disabled for `gc / clean / sample-config  and init-templatedir`. 

It now also handles the case of being run outside of a git repository by catching CalledProcessError (This is rather hacky, it would be probably better to have a utility function that checks whether or not we are inside a git repo.)

**Comment by asottile** [comment]
sorry I haven't gotten back to this, still thinking about whether eagerly or waiting for failure is the right approach here (especially as it invokes git more than I'd like to in the critical path -- and for things which previously didn't actually load the configuration / validate it)

I'm leaning towards closing this and wontfixing the original issue -- thank you either way for the PR though <3

**Comment by asottile** [comment]
I think for now I'm going to close this and the associated issue :( -- the case is rare enough and the change potentially breaks some legitimate workflows.  thank you again for taking the time to work on this and I'm sorry it didn't work out in the end <3

**Pull request closed without merging**
