### PR TITLE
add warning for deprecated stages values in `default_stages`

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
I get this warning in [CI](https://results.pre-commit.ci/run/github/68207196/1728893070.HaR7sD6ERmK6TJVVoAv8_A):
```
top-level default_stages uses deprecated stage names (commit, push) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
```
<details>
<summary>Screen capture of pre-commit.ci</summary>

default_stages
</details>

Yet running `pre-commit migrate-config` in my repository doesn't have any effect:
```console
$ pre-commit migrate-config
Configuration is already migrated.
$ 
```

**Comment by asottile** [comment]
> I get this warning in [CI](https://results.pre-commit.ci/run/github/68207196/1728893070.HaR7sD6ERmK6TJVVoAv8_A):
> 
> ```
> top-level default_stages uses deprecated stage names (commit, push) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
> ```
> 
> Screen capture of pre-commit.ci
> Yet running `pre-commit migrate-config` in my repository doesn't have any effect:
> 
> ```
> $ pre-commit migrate-config
> Configuration is already migrated.
> $ 
> ```

obviously you're not using a new enough pre-commit version

**Comment by DimitriPapadopoulos** [comment]
```console
$ pre-commit --version
pre-commit 4.0.1
$ 
```

**Comment by asottile** [comment]
show your configuration?

**Comment by DimitriPapadopoulos** [comment]
https://github.com/zarr-developers/numcodecs/blob/8edd3f96d2703df070f70bd224b3707ec4d68c4e/.pre-commit-config.yaml

The part that needs to be updated is:
```yaml
default_stages: [commit, push]
```

**Comment by asottile** [comment]
works for me

```console
$ pre-commit migrate-config
Configuration has been migrated.
$ git diff
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index dd04f38..2835f59 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -3,7 +3,7 @@ ci:
   autoupdate_commit_msg: "chore: update pre-commit hooks"
   autofix_commit_msg: "style: pre-commit fixes"
   autofix_prs: false
-default_stages: [commit, push]
+default_stages: [pre-commit, pre-push]
 default_language_version:
   python: python3
 repos:
```

**Comment by DimitriPapadopoulos** [comment]
<details>
<summary>It works on my home computer.</summary>

```console
$ grep default_stages .pre-commit-config.yaml 
default_stages: [commit, push]
$ 
$ pipx install pre-commit
  installed package pre-commit 4.0.1, installed using Python 3.10.12
  These apps are now globally available
    - pre-commit
done! ✨ 🌟 ✨
$ 
$ pre-commit --version
pre-commit 4.0.1
$ 
$ pre-commit migrate-config
Configuration has been migrated.
$ 
```
</details>

I'll retry on my computer at work tomorrow, and let you know. Either I did something wrong, or this an effect of a Linux kernel or system issue that breaks my workstation in very strange ways since it was upgraded from Ubuntu 22.04 to Ubuntu 24.04.

**Comment by asottile** [comment]
almost certainly it was an old version of pre-commit

**Comment by DimitriPapadopoulos** [comment]
I don't think it is an old version (pre-commit installed with pipx just like at home). Rather, my workstation is plagued by mysterious I/O problems since the Ubuntu 24.04 upgrade, see for example https://github.com/prefix-dev/rattler-build/issues/1045#issuecomment-2407350327.

**Comment by asottile** [comment]
I don't necessarily trust pipx to do what you want personally

**Comment by DimitriPapadopoulos** [comment]
My workstation has been reinstalled by IT. I cannot reproduce the issue any more. Sorry about the noise.

**Pull request merged**
