### PR TITLE
Moving from aspy.yaml to ruamel.yaml in order to preserve comments when using autoupdate - fixes #210

### LINKED ISSUE #210: autoupdate is awesome except it gobbles comments and reformats lists :/
This seems promising: https://pypi.python.org/pypi/ruamel.yaml/0.6

Here's their example:

```
code = ruamel.yaml.load(inp, ruamel.yaml.RoundTripLoader)
code['name']['given'] = 'Bob'
print(ruamel.yaml.dump(code, Dumper= ruamel.yaml.RoundTripDumper), end='')
```

### PR DESCRIPTION
**Pull request by Lucas-C**

### CODE REVIEW

**Comment by asottile** [comment]
So I already tried this same approach with #211 and hit a number of issues.  I have all but written off ruamel.yaml as a non solution as it was essentially trading some bugs for a bunch of other bugs.

That said,  I'd love to hear your comments on #414 where I plan to do away with yaml entirely!

**Comment by Lucas-C** [comment]
Damn. I added a comment to #414
Is #211 really blocked ?

**Comment by asottile** [comment]
'fraid so :(

**Comment by asottile** [comment]
We'll continue to explore options in #414.

**Pull request closed without merging**
