### PR TITLE
adjust relative --commit-msg-filename if in subdir

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by asottile** [comment]
@lorenzwalthert any ideas for the windows R failure here?

**Comment by lorenzwalthert** [comment]
Seems again related to missing built-time dependencies for source install, this time for transversive dependencies. Trying to enforce with #2460.

**Comment by asottile** [comment]
huh looks like I should have just clicked retry because it appears to be working now!  thanks again for checking on this!

**Comment by lorenzwalthert** [comment]
Yeah, because the dependency (without version specification) was on a package  that was not yet available as a binary.

**Pull request merged**
