### PR TITLE
Add Changelog project URL

### PR DESCRIPTION
**Pull request by scop**
Background info at
  https://github.com/pypa/warehouse/pull/7882#issue-412444446

### CODE REVIEW

**Comment by asottile** [comment]
I'd rather send people through https://pre-commit.com or https://github.com/pre-commit/pre-commit

**Comment by scop** [comment]
Hmph, unfortunate. But pre-commit.com would benefit from a direct link to the change log.

**Comment by scop** [comment]
Also, in case you're not aware, the pre-commit PyPI listing already contains both links you mentioned. This is for benefit of people doing an upgrade. It's great that there is a well maintained change log, but it's a shame it's not as prominent as it could/should.

Also #2 FWIW the mentioned warehouse issue shows that the reception for this has so far been solely positive across the bunch of projects I've filed this for, except pre-commit(-hooks) and your comment in the flake8 PR.

**Comment by asottile** [comment]
I'd be fine adding a link to pre-commit.com but it seems a little bit unnecessary to add this (and imo borderline spam to send PRs to a bunch of projects adding this).  We don't (for example) list separately the issues link or the PRs link (though those are also know by warehouse).  In my opinion, this is just more unnecessary configuration that people can already figure out by clicking through the links that are provided.

**Pull request closed without merging**
