### PR TITLE
respect aliases in SKIP when installing environments

### LINKED ISSUE #2478: SKIP skips invocation by alias but doesn't skip "Installing environment"
### search tried in the issue tracker

SKIP alias

### describe your issue

When I run 

```sh
SKIP=pylint-alias2 git commit
```

the hook aliased as `pylint-alias2` is properly skipped, however, its environment is still initialized. I would expect that it also skips the lengthy initialization of the environment.

Indeed, running a single hook ([run.py#153](https://github.com/pre-commit/pre-commit/blob/49f95b9ef391639d09136666be375d99a3dccd04/pre_commit/commands/run.py#153)) checks against `hook.id` and `hook.alias`, however `install_hook_envs` is invoked with only filtering against `hook.id` ([run.py#423](https://github.com/pre-commit/pre-commit/blob/49f95b9ef391639d09136666be375d99a3dccd04/pre_commit/commands/run.py)

Is this inconsistency deliberate? I couldn't find a use case for it. This quick and dirty patch works for us:

```diff
-        to_install = [hook for hook in hooks if hook.id not in skips]
+        to_install = [hook for hook in hooks if hook.id not in skips and hook.alias not in skips]
```

In our use case Initialization is not needed for everyone (monorepo where some non-python devs also do non-python work) and also very expensive unfortunately (6minutes currently to install already cached pip packages)

(An even better solution would be if initialization wouldn't happen at all if the hook run would we skipped in general (because of `SKIP` variable or because there is no files changed, however, that would be a but bigger patch I suppose))

### pre-commit --version

pre-commit 

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/PyCQA/pylint
    rev: v2.14.5
    hooks:
      - name: pylint-alias1
        alias: pylint-alias1
        id: pylint
        additional_dependencies:
          - arrow
      - name: pylint-alias2
        alias: pylint-alias2
        id: pylint
        additional_dependencies:
          - hdfs
```

### ~/.cache/pre-commit/pre-commit.log (if present)

_No response_

### PR DESCRIPTION
**Pull request by kmARC**
Fixes #2478

### CODE REVIEW

**Comment by asottile** [comment]
augh the company account is even worse because I can't fix the branch at all!

**Review by asottile — APPROVED** [review]

**Comment by kmARC** [comment]
> augh the company account is even worse because I can't fix the branch at all!

Hmmm... I'm not sure what do you mean by that.

I'm planning another PR that helps a lot with monorepos, but that would also come from teh company account. Do you have any guideline on how to make it easier for you?

**Comment by asottile** [comment]
(1) please do not send feature PRs without first discussing them -- monorepos have been a hot topic and I have already set my expectations that there will not be special support for them

(2) when you make PRs from organizations I cannot fixup the branch like I can with user accounts

**Comment by asottile** [comment]
and for (1) make sure to search around first -- I'm almost certain it's about `cd` and there's several discussions about this already

**Pull request merged**
