### PR TITLE
modified fixture to include auto-merge files during conflicts

### PR DESCRIPTION
**Pull request by vinayinvicible**
this is in reference to the issue pointed out in #31

### CODE REVIEW

**Comment by asottile** [comment]
So I did some research into this...

From what I can tell it is not possible to differentiate between auto-merged files and manually-merged files without actually re-running the merge (which would be expensive and fragile).  So on one point I don't think it's actually possible to exclude auto-merged files.

On the other hand, I don't think we want to exclude auto-merged files.  In the general case, both sides should have already used best practices and have passing hooks.  But also, it is often useful to identify implicit conflicts (one common one we hit _all the time_ at yelp is someone factors some import out of a file and someone else adds a new usage of that import.  Despite both passing the hooks and the merge succeeding, there's now an undefined reference to something that used to be defined.

Given that, how would you feel about me updating the test to incorporate this diff (just for documentation / spec purposes) and adding some documentation around this (since it is currently unspecified and unclear).

**Comment by vinayinvicible** [comment]
that import example is a solid argument. :+1: 

you should definitely modify docs regarding this

**Comment by vinayinvicible** [comment]
@asottile On second thought, shouldn't you be running pre-commit on pure merge commits also (same argument as yours')

**Comment by asottile** [comment]
Nah you won't have 2 inputs to cause an implicit conflict

**Comment by asottile** [comment]
ah, I see what you mean.  Yeah it should run on merge commits (that contain auto-merged files) but git doesn't give us a hook :(

**Comment by asottile** [comment]
As discussed (and documented via https://github.com/pre-commit/pre-commit.github.io/pull/80)

**Pull request closed without merging**
