### PR TITLE
fix: add ability to provide a file with excludes

### PR DESCRIPTION
**Pull request by cesan3**
This resolves: #3059

### CODE REVIEW

**Comment by asottile** [comment]
feature was never agreed upon -- don't waste time implementing features until they've been agreed upon

**Comment by cesan3** [comment]
Hmm, just a thought, having the ability to extend the configuration using external files could help a lot with integration with other tools and frameworks.

**Comment by asottile** [comment]
no it would not.  it would create a bunch of maintenance work for me for little to no gain

**Comment by DrMarkEy** [comment]
Just my 2 cents: My project already has a CI pipeline set up, which uses files with excludes for some linting jobs.
If I now want to use pre-commit for my local setup, I would have to copy all these excludes to the config file, translate them from glob patterns to regular expressions and from now on maintain both lists in parallel. This is a huge pain and currently a showstopper for me. I would really appreciate this feature a lot!

**Comment by asottile** [comment]
you don't though

pre-commit only runs on checked in files and you can run it in ci

**Pull request closed without merging**
