### PR TITLE
Factor out bash and activate files

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by asottile** [comment]
Seems I'll need to implement #345 to make this work on windows

**Comment by asottile** [comment]
hmmm, one side-effect of factoring out xargs is shebangs aren't processed on windows... I guess I could try and implement that as well (ick)...

**Comment by asottile** [comment]
https://github.com/polysquare/python-parse-shebang seems promising for fixing the shebang issues

**Comment by asottile** [comment]
Soooooo close.  I seem to be blocked on getting full pcre support on windows: https://github.com/Alexpux/Cygwin/issues/15

**Comment by chriskuehl** [comment]
(wait for it)

**Comment by asottile** [comment]
Reported the pcre bug here: https://cygwin.com/ml/cygwin/2016-04/msg00157.html

**Pull request merged**
