### PR TITLE
Add pre-commit badge

### PR DESCRIPTION
**Pull request by ddelange**
Since I like pretty badges, I decided to request your logo be added to simple-icons (https://github.com/simple-icons/simple-icons/issues/2475) for use with shields.io.

Since I think badges are a perfect way to promote technologies and provide insights, I wanted [your badge to shine](https://github.com/ddelange/pipgrip#development) as well. Having it in your README will maybe also inspire other devs to adopt it and spread the word!

I'm also interested in other wordings than `enabled` or `available`, maybe you have a nice idea?

### CODE REVIEW

**Comment by asottile** [comment]
neat!  let's add this to the docs instead: https://github.com/pre-commit/pre-commit.github.io -- https://github.com/pre-commit/pre-commit.github.io/issues/194

(I personally don't really like adding badges to my READMEs but I think others would appreciate this!)

can add some sample markdown / rst / etc. as well -- let me know if you'd like some help documenting this and greatly appreciate the work you've put into this :tada:

**Comment by ddelange** [comment]
Sure! I'll open a PR for the website. Would you like to merge this PR anyway? I think this will be the landing page for many people (e.g. all the people that will be clicking the badge ^^). Or would you like to link it to pre-commit.com?

I'll add the badge on pre-commit.com. Can you give me a gitlink to where you would like to see a code block with badge code examples?

**Comment by asottile** [comment]
yeah we can have just this one -- let me find where we'd want to put this in the docs :thinking:

**Comment by asottile** [comment]
can probably add it right before this section here: https://github.com/pre-commit/pre-commit.github.io/blob/4250dada78f819b59b20a6d80027178fb7797cc1/index.mako#L1432

I think linking to github is fine, that way they can star and click through to the docs if they want

**Pull request merged**
