### PR TITLE
Use ggrep instead of grep for pcre on mac os

### PR DESCRIPTION
**Pull request by tdeo**
This fixes issue https://github.com/pre-commit/pre-commit/issues/133

### CODE REVIEW

**Comment by tdeo** [comment]
This requires ggrep installed on the machine by `brew install grep`. I don't know on which readme that should be indicated ?

**Comment by asottile** [comment]
Thanks for the pr!

We cab probably add this information to http://github.com/pre-commit/pre-commit.github.io

**Comment by tdeo** [comment]
Just sent the PR. Do you have any idea when you will release that ?

Thanks

**Comment by asottile** [comment]
Just released 0.5.5 :)

Thanks again!

**Pull request merged**
