### PR TITLE
Compute the maximum command length more accurately

### LINKED ISSUE #691: Improve platform command line length limits
I have a question related to #510 

When I run `pre-commit run` all hooks work as expected (processing just changed files), but `pre-commit run -a` divides a list of files into 5 bulks and run the same hook in parallel executions. This creates unnecessary checks of files which belong to the same directory.

Is it possible to control that certain hooks should not be executed in parallel but rather pass all filenames to it?

Alternatively, is there an environment variable or something like that which says that pre-commit is running a hook for all files?

### PR DESCRIPTION
**Pull request by asottile**
Resolves #691 

- [x] try this out on linux
- [x] try this out on macos
- [x] try this out on windows
- [x] try this out on cygwin

### CODE REVIEW

**Comment by asottile** [comment]
Sourced a lot of the information from https://www.in-ulm.de/~mascheck/various/argmax/

**Comment by asottile** [comment]
cygwin and macos fall into the `posix` branch, `cygwin` sets `SC_ARG_MAX` to `32000` which performs basically the same math as the `nt` pathway.  macos seems to report a reasonable value there as well

**Comment by ashanbrown** [comment]
Thanks @asottile.  Sorry not to get around to testing it.

**Comment by asottile** [comment]
No big deal!  Thanks for the original work on this :)

I ended up testing it on my work computer (and last night purchased an old mac mini so hopefully I can test it more readily in the future)

**Pull request merged**
