### PR TITLE
include checking symlinks

### PR DESCRIPTION
**Pull request by bchess**
os.path.exists -> os.path.lexists so that we also check symlink files

### CODE REVIEW

**Comment by asottile** [comment]
:shipit: once appveyor is done I'll merge and cut a version for ya :)

**Comment by chriskuehl** [comment]
this is kinda dangerous if you have symlinks pointing outside the repo, most hooks won't expect that :(

hopefully #329 will fix that, i'll try to finish up remaining issues soon

**Comment by asottile** [comment]
It's no less dangerous than *working* symlinks which point outside the repo (status quo)

**Comment by chriskuehl** [comment]
@asottile you're right, misinterpreted this change

**Comment by asottile** [comment]
This is available in v0.7.5

**Pull request merged**
