### PR TITLE
Added support for Powershell

### PR DESCRIPTION
**Pull request by WallucePinkham**
Added support for powershell as 3rd class language.

### CODE REVIEW

**Comment by WallucePinkham** [comment]
I don't understand how my changes broke tests for go?

**Comment by asottile** [comment]
is this needed? I've seen PowerShell based hooks work fine with `language: script` and `language: system`

**Comment by WallucePinkham** [comment]
> is this needed? I've seen PowerShell based hooks work fine with `language: script` and `language: system`

Could you please provide some examples of how this worked? I couldn't manage to make it work with script or system, but I would be happy for some advice.

**Comment by asottile** [comment]
for example:

```console
PS C:\Users\Anthony\workspace\pwsh-example> tail -n 999 .pre-commit-config.yaml bin/example.ps1
==> .pre-commit-config.yaml <==
repos:
-   repo: local
    hooks:
    -   id: pwsh
        name: pwsh
        entry: bin/example.ps1
        language: script
        always_run: true
        pass_filenames: false
        verbose: true

==> bin/example.ps1 <==
#!/usr/bin/env powershell
Write-Host "hello world"


PS C:\Users\Anthony\workspace\pwsh-example> pre-commit run --all-files
pwsh.....................................................................Passed
- hook id: pwsh
- duration: 0.18s

hello world
```

**Comment by WallucePinkham** [comment]
Thanks so much!

**Comment by asottile** [comment]
closing given above!

**Pull request closed without merging**
