### PR TITLE
Support GN build language

### PR DESCRIPTION
**Pull request by KindDragon**
GN is a meta-build system that generates build files for Ninja

See also https://gn.googlesource.com/gn/

I create it based on golang language, but simplify it a bit. Main purpose of this language to create hook for `gn format`

### CODE REVIEW

**Comment by asottile** [comment]
if your goal is to just make a hook for `gn` -- it probably doesn't make sense as a language

you can build something similar to https://github.com/shellcheck-py/shellcheck-py -- basically you'd be writing a small python package around it and use [setuptools-download](https://github.com/asottile/setuptools-download) to ensure the binary is available

optionally you can publish that to pypi as well -- that'd make it super simple to `pip install gn-py` as well!

**Comment by KindDragon** [comment]
BTW why you not allowing `language: docker`, or `language: docker_image` hooks at [pre-commit.com](https://github.com/pre-commit/pre-commit.com/tree/main)
/all-repos.yaml?

**Comment by asottile** [comment]
native installation provides a better user experience. installation at runtime is unsupported and can corrupt the cache

**Comment by KindDragon** [comment]
Ok, thanks. But I think it's better in the future Implement for something like `entry_install` and `entry_uninstall` for `language: script` to reduce such unnecessary python packages when you just need to download binaries

**Comment by asottile** [comment]
if you search the issue tracker you'll find such a suggestion already

**Pull request closed without merging**
