### PR TITLE
Fix for creating a new python virtualenv inside a virtualenv/venv

### PR DESCRIPTION
**Pull request by marcelotduarte**
This fixes a bug similar to that reported in issues #2525 #2503 and #2299.

### CODE REVIEW

**Comment by asottile** [comment]
no this isn't right or the right place to fix a bug in debian

**Comment by marcelotduarte** [comment]
I meant similar because I'm using ubuntu 22.04, python 3.10.6
The fixes reported in the issues do not solve my issue because it is different.
And I don't understand why you can't get around a problem if you have a solution. This prevents us from continuing to use a great tool you've developed. I work on an open-source project and I really like it when you have a solution that makes life easier for others.

**Comment by asottile** [comment]
I promise you the solutions for 22.04 and 3.10.4 also work for 3.10.6 because I am using them

**Comment by asottile** [comment]
and I'm case you're having a hard time with the threads because there's admittedly a lot of them because it's a common problem: install python3-distutils and then clear the virtualenv cache in ~/.local/share

also your patch is not a good one and breaks windows

**Pull request closed without merging**
