### PR TITLE
Update sample config pre-commit-hooks version to v4.0.1

### PR DESCRIPTION
**Pull request by iwt-dennyschaefer**
Update **sample config** `pre-commit-hooks` version to `v4.0.1`

### CODE REVIEW

**Comment by asottile** [comment]
this doesn't need to be up to date and isn't terribly out of date

**Comment by iwt-dennyschaefer** [comment]
>this doesn't need to be up to date and isn't terribly out of date

It's one major version behind :thinking: 

I used the sample config to start with `pre-commit` in many of our repositories, now I have to spend time again to update the **hook** to the latest version which is quite time-consuming.

If in your opinion this pull request is not needed please close it.

**Comment by asottile** [comment]
fortunately `pre-commit autoupdate` is very easy to run, or if you're using https://pre-commit.ci it'll do it automatically

**Comment by asottile** [comment]
or if you're not, [all-repos](https://github.com/asottile/all-repos) has an autofixer to generate autoupdate prs

**Comment by iwt-dennyschaefer** [comment]
> fortunately pre-commit autoupdate is very easy to run

This is what I used in the end, thx for this very helpful hint :+1: 

> or if you're not, all-repos has an autofixer to generate autoupdate prs

Thx, I will definitely take a look into this. :telescope:

**Pull request closed without merging**
