### PR TITLE
Add MANIFEST file to include license in sdist

### LINKED ISSUE #745: Include LICENSE in sdist
Hi @asottile!

I'm creating a conde package for `pre-commit` and noticed that the `sdist` uploaded to PyPI does not contain the `LICENSE` file. It would be nice to include it so other packagers based on the `sdist` can include the license file as well.

### PR DESCRIPTION
**Pull request by nicoddemus**
Fix #745

### CODE REVIEW

**Comment by asottile** [comment]
Thanks! this should make it into the next release, planning to get https://github.com/pre-commit/pre-commit/pull/739 done first :)

**Comment by nicoddemus** [comment]
Great, thanks! 😁

**Comment by artcyb** [comment]
😉

**Comment by asottile** [comment]
This has been released as part of [v1.9.0](https://github.com/pre-commit/pre-commit/releases/tag/v1.9.0)!

**Comment by nicoddemus** [comment]
Cool, thanks!

**Pull request merged**
