### PR TITLE
Fix pre-commit when python-future is installed and a py3 virtualenv is being created

### PR DESCRIPTION
**Pull request by asottile**
Using http://github.com/asottile/virtualenv-hax in place of virtualenv to work around https://github.com/PythonCharmers/python-future/issues/148

### CODE REVIEW

**Comment by chriskuehl** [comment]
please no

**Comment by asottile** [comment]
Seems no longer necessary with latest virtualenv

**Comment by asottile** [comment]
now to get yelp to upgrade...

**Pull request closed without merging**
